stages:
  fetch-metadata:
    cmd: python scripts/fetch_eidc_metadata.py ${files.metadata}
    deps:
    - scripts/fetch_eidc_metadata.py
    outs:
    - ${files.metadata}
  extract-metadata:
    cmd: python scripts/extract_metadata.py ${files.metadata} ${files.extracted}
    deps:
    - ${files.metadata}
    - scripts/extract_metadata.py
    outs:
    - ${files.extracted}
  chunk-data:
    cmd: python scripts/chunk_data.py -o ${files.chunked} -c ${hp.chunk-size} -ol ${hp.overlap} -s ${sample-size} ${files.extracted}
    deps:
    - ${files.extracted}
    - scripts/chunk_data.py
    outs:
    - ${files.chunked}
  create-embeddings:
    cmd: python scripts/create_embeddings.py ${files.chunked} ${files.embeddings}
    deps:
    - ${files.chunked}
    - scripts/create_embeddings.py
    outs:
    - ${files.embeddings}
  upload-to-docstore:
    cmd: python scripts/upload_to_docstore.py ${files.embeddings} -o ${files.doc-store} -em ${hp.embeddings-model}
    deps:
    - ${files.embeddings}
    - scripts/upload_to_docstore.py
    outs:
    - ${files.doc-store}
  run-rag-pipeline:
    cmd python scripts/run_rag_pipeline.py ${files.test-set}
    