stages:
  fetch-metadata:
    cmd: python scripts/fetch_eidc_metadata.py data/eidc_metadata.json
    deps:
    - scripts/fetch_eidc_metadata.py
    outs:
    - data/eidc_metadata.json
  prepare:
    cmd: python scripts/prepare_data.py data/eidc_metadata.json data/prepared_eidc_metadata.json
    deps:
    - data/eidc_metadata.json
    - scripts/prepare_data.py
    outs:
    - data/prepared_eidc_metadata.json
