stages:
  fetch-metadata:
    cmd: python scripts/fetch_eidc_metadata.py ${files.metadata} -s ${sub-sample}
    deps:
    - scripts/fetch_eidc_metadata.py
    outs:
    - ${files.metadata}
  fetch-supporting-docs:
    cmd: python scripts/fetch_supporting_docs.py ${files.metadata} ${files.supporting-docs}
    deps:
    - ${files.metadata}
    - scripts/fetch_supporting_docs.py
    outs:
    - ${files.supporting-docs}
  extract-metadata:
    cmd: python scripts/extract_metadata.py ${files.metadata} ${files.extracted}
    deps:
    - ${files.metadata}
    - scripts/extract_metadata.py
    outs:
    - ${files.extracted}
  chunk-data:
    cmd: python scripts/chunk_data.py -o ${files.chunked} -c ${hp.chunk-size} -ol ${hp.overlap} ${files.extracted} ${files.supporting-docs}
    deps:
    - ${files.extracted}
    - ${files.supporting-docs}
    - scripts/chunk_data.py
    outs:
    - ${files.chunked}
  create-embeddings:
    cmd: python scripts/create_embeddings.py ${files.chunked} ${files.embeddings}
    deps:
    - ${files.chunked}
    - scripts/create_embeddings.py
    outs:
    - ${files.embeddings}
  upload-to-docstore:
    cmd: python scripts/upload_to_docstore.py ${files.embeddings} -o ${doc-store.files} -em ${hp.embeddings-model} -c ${doc-store.collection}
    deps:
    - ${files.embeddings}
    - scripts/upload_to_docstore.py
    outs:
    - ${files.doc-store}
  generate-testset:
    cmd: cp data/synthetic-datasets/eidc_rag_test_sample.csv data/
    outs: 
    - ${files.test-set}
  run-rag-pipeline:
    cmd: python scripts/run_rag_pipeline.py ${files.test-set} ${files.eval-set} ${files.doc-store} -c ${doc-store.collection}
    deps:
    - ${files.test-set}
    - ${files.doc-store}
    - scripts/run_rag_pipeline.py
    outs: 
    - ${files.eval-set}
  evaluate:
    cmd: python scripts/evaluate.py ${files.eval-set} -m ${files.metrics} -img ${files.eval-plot}
    deps:
    - ${files.eval-set}
    - scripts/evaluate.py
    outs:
    - ${files.metrics}
    - ${files.eval-plot}
metrics: 
- ${files.metrics}