hp:
  chunk-size: 300
  overlap: 100
  embeddings-model: "all-MiniLM-L6-v2"
files:
  metadata: "data/eidc_metadata.json"
  extracted: "data/extracted_metadata.json"
  chunked: "data/chunked_data.json"
  embeddings: "data/embeddings.json"
  doc-store: "data/chroma-data"
sample-size: 10 # sample size of 0 will process all data