[project]
name = "llm-eval"
dynamic = ["version"]

dependencies = [
    "plotly",
    "pandas",
    "numpy",
    "kaleido",
    "dvc",
    "dvc[s3]",
    "vllm",
    "bitsandbytes",
    "haystack-ai",
    "accelerate",
    "sentence-transformers",
    "chromadb",
    "ollama-haystack == 0.0.7",
    "chroma-haystack",
    "ragas == 0.1.10",
    "nltk",
    "nbformat>=4.2.0",
    "ruff",
    "mypy",
    "types-requests",
    "types-tqdm",
    "pandas-stubs",
]

[project.optional-dependencies]
jupyter = [
    "ipykernel",
    "ipywidgets",
]

[tool.setuptools]
py-modules = []

[tool.mypy]
files = ["scripts"]