[project]
name = "llm-eval"
dynamic = ["version"]

dependencies = [
    "plotly",
    "pandas",
    "numpy",
    "kaleido",
    "dvc",
    "dvc[s3]",
    "vllm",
    "bitsandbytes",
    "haystack-ai",
    "accelerate",
    "sentence-transformers",
    "chromadb",
    "ollama-haystack == 0.0.7",
    "chroma-haystack",
]

[project.optional-dependencies]
jupyter = [
    "ipykernel",
    "ipywidgets",
]

[tool.setuptools]
py-modules = []
