[project]
name = "llm-eval"
dynamic = ["version"]

dependencies = [
    "plotly == 5.24.1",
    "pandas == 2.2.3",
    "numpy == 1.26.4",
    "kaleido == 0.2.1",
    "dvc[s3] == 3.2.0 ",
    "bitsandbytes == 0.44.1",
    "haystack-ai == 2.6.0",
    "accelerate == 1.0.0",
    "sentence-transformers == 3.1.1",
    "chromadb == 0.5.15",
    "ollama-haystack == 0.0.7",
    "chroma-haystack == 0.22.1",
    "ragas == 0.1.10",
    "nltk == 3.9.1",
    "nbformat == 4.2.0",
    "ruff == 0.7.0",
]

[project.optional-dependencies]
jupyter = [
    "ipykernel",
    "ipywidgets",
]

[tool.setuptools]
py-modules = []
