name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - uses: iterative/setup-cml@v2
      - name: Run pipeline
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uv sync
          uv run dummy-evaluation.py

          # Create CML report
          cat metrics.txt >> report.md
          echo '![](./metrics.png "Violin Plot of Metrics")' >> report.md
          cml comment create report.md
