name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: iterative/setup-cml@v2
      - name: Run pipeline
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install .
          python dummy-evaluation.py

          # Create CML report
          cat metrics.txt >> report.md
          echo '![](./metrics.png "Violin Plot of Metrics")' >> report.md
          cml comment create report.md
          