name: CML
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Run pipeline
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install .
          python dummy-evaluation.py

          # Create CML report
          cat metrics.txt >> report.md
          echo '![](./metrics.png "Violin Plot of Metrics")' >> report.md
          cml comment create report.md
          